package com.example.lucas.homework2;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.cs407.tylerphelps.cs407hw2.CalEvent;

import com.cs407.tylerphelps.cs407hw2.CalEventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig calEventDaoConfig;

    private final CalEventDao calEventDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        calEventDaoConfig = daoConfigMap.get(CalEventDao.class).clone();
        calEventDaoConfig.initIdentityScope(type);

        calEventDao = new CalEventDao(calEventDaoConfig, this);

        registerDao(CalEvent.class, calEventDao);
    }

    public void clear() {
        calEventDaoConfig.getIdentityScope().clear();
    }

    public CalEventDao getCalEventDao() {
        return calEventDao;
    }

}
